const pubkey = `
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDpxv+yCAYuwXCSxLviAFyiy3V0
rvveRTbzt4KKASqzbwSJ4Kst73HFFka5GaI4nnQZQt4OzJUD3jNYKphE6WdDpSEJ
VuTbIzEoV0j9AS56gCF0YP8o8vTT3hQm2WtS+biG7sxJgDefdaWSaN6utwFZFfTh
RvBBeuOMIPb6X60lIwIDAQAB
-----END PUBLIC KEY-----`
export default  pubkey
