const pubkey = `
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCCKIBwiqF0BDO0Lb0BnK2OSpxQMU12lTKHTpl9VFoQEtcGpKOL3PK8x/irOApTbD42sFOi2rOiXu/oVcVI4jkhKf9l3ziWCkCQ070ONBEzd7gwiEaI2OHpszgndjXIRukuyBTyWZUhsdopHMJO6mejZlVSr6DeeP63w+RMftTksQIDAQAB
-----END PUBLIC KEY-----`
export default  pubkey
